{% set name = "smartypants" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8db97f7cbdf08d15b158a86037cd9e116b4cf37703d24e0419a0d64ca5808f0d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.0

  run:
    - python >=3.0

test:
  imports:
    - smartypants

about:
  home: https://github.com/leohemsted/smartypants.py
  license_file: COPYING
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Python with the SmartyPants'
  dev_url: https://github.com/leohemsted/smartypants.py
  doc_url: https://pythonhosted.org/smartypants/

extra:
  recipe-maintainers:
    - pmlandwehr
    - thewchan
