{% set name = "smartypants" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7812353a32022699a1aa8cd5626e01c94a946dcaeedaee2d0b382bae4c4cbf36

build:
  noarch: python
  number: 2
  script: python -m pip install . -vvv

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - smartypants

about:
  home: https://bitbucket.org/livibetter/smartypants.py
  license_file: COPYING
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Python with the SmartyPants'
  dev_url: https://bitbucket.org/livibetter/smartypants.py
  doc_url: https://pythonhosted.org/smartypants/

extra:
  recipe-maintainers:
    - pmlandwehr
