# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "TyAYZCav0Z9BmUB7pq5LPK8SK5TtefgjdF6sCebifgg09K72qw8WpH9JQJxTTUiK2LTtjr/LB6wnoGOoHG77bt3rRyLa3iMRek070YF1xbZo5oYI9TiddVnbnVL96yWSbU1JKrLkCCJbkPVYTw72XFZVDahZaUPo69sm7mhK3uHgQiNYOdWE1BKidivTN1GAcVk4OBByW1gy9qNpgZxR4AqGgnSeRaaYNIRnxfqwcx+NcV7htSAIzTdrd6bctXsUK3PsHbuDShueV6e6HzxJbXDbTHt/Cth0j9C7NTvsklCPHi55LXqVLbVBpLY2/QY4jgOM06Vi/ZXnb+lsq21+K3a2b+23jGYXoU6zw8teBWCN05fvTNeiNEyWjsZJrx4amTUbcWP4ITug3Ki6svOhbAiio50hM4jDzCKU9/9vNkNRTWVH+mjSbf4qXTzoUJZuZARMXhJsPy0HnfHNjdlEAehA9r1jkweWi2pG/rQYgMYrva+nQDz20HGs/2/16Yz7QGh3QfwF3ojCA1HgWZRsHkjDYgTTDCGWxf4OLZzRQypRvTuQR7d3rDOw8KfJWvWz/3Ymh04EMmrXNUkw3u7PWz5E/W3expj+oS6zaTbjJBM4lYLAoG6mBaWKUUjL7BPAv4Rtpwv4wUsVG6hnJLygXIILAnMmisHpa8F4FpAW4uI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
