travis:
  secure:
    BINSTAR_TOKEN: gogGENig7efUKiwu7aoFzOHY6PhPbm2e7TZLtQlbdDk1gQPZWD9na7dA5ksC9D41NYu69jGi3JkQd3XCxvTJXDvRsyFjPfv9e3jTicZeLupz9v9/V+IY+WHD7h2nFYXKKVOsrYlSkwaMhOKiTdNmbRv2fPT27Juu+qF9uCKD9+HxEsLHgyxAVEs4OpwMcZXh+CndV0zYrApQjiINK//kPZG1zoq/XVJYQvTi7MfOO8P5RzCZdIoylZ1DB3t/f21Bz6i6taJleJ7tgTIfGrWdVvMDw8V4fIiBGCbQ9/WMpvDeubOWcXpB42RztILJc4ZYXqPaZvgl3dPwfMnoDUmCSk8l8o9x4+cEn6zGfi8F3RYvaRZOSq7elJyN0D1ZD/G8Y9itu1EjbNtq31nGaqyodD5D8r1c/f4U7rJOHm1jifwK8XDG4uY0PYzfmNOXE02ZEGpJU09c6DTYRZt1IGExP5VEedI0qycRRIsvIBNuQwT8SYF3tIt8zLOvCe7moYiO42ZETLkIZHUY9fp638ljjpW3RW/b3LMSsV4EsTJhYGDS6GoBBkq1Dy9H5TxuAUl5JHsMtXaoZy3P2s5OvAhvRP6RK0qKRbwVPK+hQD/BiXkSioxs8HTy79JSzifebQgk4L3eiIk9NzAudbtStMGbcRks2WC7Rk/5q/zER9KQ4/s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
