travis:
  secure:
    BINSTAR_TOKEN: PYwVSQLZrsMvbCm1C5NeKkqHRfjUk7/A7wHTl8K5AYqkutL40+ly7820g6J/TZ/2FGhP9lGseZFCeh4/ebTIV6TbJ5tI9VXunGzVDnH1rShVAlYXFPdpMaLk/J02Uxwiry9lrcZRp6ZqngJJmN2CnWkWQuBZ+R4oJW0b+txPT09todPKL55LnZehbKV7fT5f7qaGXNlJtcnHLfTKo4XhSmJcn+ABwd4zmMB5vCzLgrxHQJCn+Fzy9V3t/u0hcoXX4GdCLby8cRq3jTr3UTtRmiTbESyU1bz822RWKhk86iunZ/CCPf2vpaQcdgeHBeS7v9Q3XaGW851u3Yst5p9+txC9Reag3xfZUdL/07VsUWzf0QaFKUFSYrb6kQWtnfVtMadGhe8rW0UEDCJ1jWqzR4SNnIIiNVBZzhxlW9vCAqfYaQuKsDQlcNJPzazoTGfyjhQqZmUD8KPiZOE3izJyXKxZSMCspS9OEoodysAJ1PANoy2ByG+g2XnifypJ3tRBMRTEY2WvKMQu+vmYNy4Axu3aMMG6F0Sl0dhIN5cF2YstPGqH/HLSgpAuvLbUiaEA54HsXAxrKD50OppkhiHHUv1Sk2aSZfsG0WYVUy/EHJhJtX//OMvzbtPJUAZvPuZ4YsBc0J9UwweMJEMurR9kpL4VHb4Nurvb1/9LEfnEMHk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
