travis:
  secure:
    BINSTAR_TOKEN: TyAYZCav0Z9BmUB7pq5LPK8SK5TtefgjdF6sCebifgg09K72qw8WpH9JQJxTTUiK2LTtjr/LB6wnoGOoHG77bt3rRyLa3iMRek070YF1xbZo5oYI9TiddVnbnVL96yWSbU1JKrLkCCJbkPVYTw72XFZVDahZaUPo69sm7mhK3uHgQiNYOdWE1BKidivTN1GAcVk4OBByW1gy9qNpgZxR4AqGgnSeRaaYNIRnxfqwcx+NcV7htSAIzTdrd6bctXsUK3PsHbuDShueV6e6HzxJbXDbTHt/Cth0j9C7NTvsklCPHi55LXqVLbVBpLY2/QY4jgOM06Vi/ZXnb+lsq21+K3a2b+23jGYXoU6zw8teBWCN05fvTNeiNEyWjsZJrx4amTUbcWP4ITug3Ki6svOhbAiio50hM4jDzCKU9/9vNkNRTWVH+mjSbf4qXTzoUJZuZARMXhJsPy0HnfHNjdlEAehA9r1jkweWi2pG/rQYgMYrva+nQDz20HGs/2/16Yz7QGh3QfwF3ojCA1HgWZRsHkjDYgTTDCGWxf4OLZzRQypRvTuQR7d3rDOw8KfJWvWz/3Ymh04EMmrXNUkw3u7PWz5E/W3expj+oS6zaTbjJBM4lYLAoG6mBaWKUUjL7BPAv4Rtpwv4wUsVG6hnJLygXIILAnMmisHpa8F4FpAW4uI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
